/*
 * Copyright (c) 2025 Logan Ryan McLintock
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */


#ifndef ADDRESS_H
#define ADDRESS_H

#define KERNEL_ADDRESS 0x200000
#define KERNEL_SPACE_VIRTUAL_ADDRESS 0xffff800000000000
#define KERNEL_VIRTUAL_ADDRESS (KERNEL_SPACE_VIRTUAL_ADDRESS + KERNEL_ADDRESS)

#define VIDEO_ADDRESS 0xb8000
#define VIDEO_VIRTUAL_ADDRESS (KERNEL_SPACE_VIRTUAL_ADDRESS + VIDEO_ADDRESS)

#define PML4_ADDRESS 0x70000
#define PML4_VIRTUAL_ADDRESS (KERNEL_SPACE_VIRTUAL_ADDRESS + PML4_ADDRESS)
#define PML4E_VIRTUAL_IDENTITY PML4_VIRTUAL_ADDRESS


#endif
