;
; Copyright (c) 2024, 2025 Logan Ryan McLintock
;
; Permission to use, copy, modify, and/or distribute this software for any
; purpose with or without fee is hereby granted, provided that the above
; copyright notice and this permission notice appear in all copies.
;
; THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
; WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
; MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
; ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
; WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
; ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
; OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
;

; Shared definitions for Toucanix.

; Newline character.
NL equ 10

DISK equ 0x80
DISK_ADDRESS_PACKET_SIZE equ 16
EXTENDED_READ_FUNCTION_CODE equ 0x42
BIOS_DISK_SERVICES equ 0x13

MBR_SECTOR equ 1
PRINT_SECTORS equ 1
LOADER_SECTORS equ 2
KERNEL_SECTORS equ 120

PRINT_START_SECTOR equ MBR_SECTOR
LOADER_START_SECTOR equ PRINT_START_SECTOR + PRINT_SECTORS
KERNEL_START_SECTOR equ LOADER_START_SECTOR + LOADER_SECTORS

BYTES_PER_DOUBLE_WORD equ 4
BYTES_PER_SECTOR equ 512

MBR_ADDRESS equ 0x7c00
PRINT_ADDRESS equ MBR_ADDRESS + (MBR_SECTOR * BYTES_PER_SECTOR)
LOADER_ADDRESS equ PRINT_ADDRESS + (PRINT_SECTORS * BYTES_PER_SECTOR)




VIDEO_ADDRESS equ 0xb8000
VIDEO_SEGMENT equ VIDEO_ADDRESS / 16

ROW equ PRINT_ADDRESS
COL equ PRINT_ADDRESS + 4
PRINT_FUNC equ COL + 4


KERNEL_ORIGINAL_ADDRESS equ 0x10000
KERNEL_ORIGINAL_SEGMENT equ KERNEL_ORIGINAL_ADDRESS / 16
KERNEL_ORIGINAL_OFFSET equ KERNEL_ORIGINAL_ADDRESS % 16

KERNEL_SIZE equ KERNEL_SECTORS * BYTES_PER_SECTOR

KERNEL_ADDRESS equ 0x200000

; Start of the higher 48-bit canonical address region.
KERNEL_SPACE_VIRTUAL_ADDRESS equ 0xff_ff_80_00_00_00_00_00
KERNEL_VIRTUAL_ADDRESS equ KERNEL_SPACE_VIRTUAL_ADDRESS + KERNEL_ADDRESS


; Colours.
RED equ 4

; Light.
GREY equ 7
GREEN equ 0xa

MAGENTA equ 5
YELLOW equ 0xe

YELLOW_ON_MAGENTA equ MAGENTA << 4 | YELLOW


USER_RING equ 3

PRESENT_BIT_SET                 equ 1 << 7
DESCRIPTOR_PRIVILEGE_LEVEL_USER equ USER_RING << 5
TYPE_IS_CODE_OR_DATA_SEGMENT    equ 1 << 4
EXECUTABLE                      equ 1 << 3
CODE_READ_OR_DATA_WRITE_ACCESS  equ 1 << 1


CODE_ACCESS_BYTE equ PRESENT_BIT_SET  \
    | TYPE_IS_CODE_OR_DATA_SEGMENT    \
    | EXECUTABLE

GRANULARITY_4_KIB   equ 1 << 3
SIZE_32_BIT_SEGMENT equ 1 << 2
LONG_MODE_CODE      equ 1 << 1

NULL_SEGMENT equ 0
CODE_SEGMENT_INDEX equ 1
CODE_SELECTOR equ CODE_SEGMENT_INDEX << 3
